name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - name: Hello step
        run: echo "Hello World!"

      - name: Date now
        run: date

      - name: Directory contents
        run: ls -l