name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm i
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: heroku-deploy
        uses: akhileshns/heroku-deploy@v3.8.9
        if: ${{github.event_name == 'push'}}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.MY_EMAIL}}
          healthcheck: "https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/health"
          checkstring: ok
          rollbackonhealthcheckfailed: true
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        if: ${{github.event_name == 'push'}} && env.COMMIT_MESSAGES_NOT_CONTAINS_SKIP
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DEFAULT_BUMP: patch
          COMMIT_MESSAGES_NOT_CONTAINS_SKIP: ${{ ! contains(join(github.event.commits.*.message, ''), '#skip') }}
      - name: The job has succeeded
        uses: 8398a7/action-slack@v3
        fields: repo,message,commit,author,eventName,ref,workflow,job,took
        custom_payload: |
          {
            username: 'github_action',
            attachments: [{
              color: 'good',
              text: `Job succeded in ${process.env.AS_TOOK}`,
            }]
          }
        if: ${{ success() }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: The job has failed
        uses: 8398a7/action-slack@v3
        fields: repo,message,commit,author,eventName,ref,workflow,job,took
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}