name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: commit messages - toJson, join
        env:
          COMMIT_MESSAGES: ${{ join(toJson(github.event.commits.*.message)) }}
        run: echo "$COMMIT_MESSAGES"
      - name: commit messages - join, toJson
        env:
          COMMIT_MESSAGES: ${{ toJson(join(github.event.commits.*.message)) }}
        run: echo "$COMMIT_MESSAGES"
      - name: commit messages - just join
        env:
          COMMIT_MESSAGES: ${{ join(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: commit messages contains '#fghj'
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        if: contains(env.COMMIT_MESSAGES, '#fghj')
        run: echo yes it does
      - name: commit messages does not contain '#fghj'
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        if: (! contains(env.COMMIT_MESSAGES, '#fghj'))
        run: echo no it doesnt